export const homeBanners = [
  {
    id: 7,
    name: "AI Begins with data",
    description: "AI Begins with data",
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: "",
    subheading: "",
    link: '/home/pre-summit-events/apply',
    buttonText: "",
    isClickable: true,
    isExternal: false,
    confirmationText: "",
    popupText: "",
    screenName: "",
    weight: 2,
    files: {
      desktop: {
        filePath: "images/w-summit(latest).png",
        fileName: "w-summit.png",
        fileExtension: ".png",
        fileUrl: "images/w-summit(latest).png",
      },
      tablet: {
        filePath: "images/t-summit(latest).png",
        fileName: "t-summit.png",
        fileExtension: ".png",
        fileUrl: "images/t-summit(latest).png",
      },
      mobile: {
        filePath: "images/m-summit(latest).png",
        fileName: "m-summit.png",
        fileExtension: ".png",
        fileUrl: "images/m-summit(latest).png",
      },
    },
    status: true,
    createdAt: "2025-05-05T06:44:30.587Z",
    updatedAt: "2025-05-06T07:41:50.393Z",
    createdBy: "342f5142-0955-4053-9c13-caac0104cf2c",
    updatedBy: "342f5142-0955-4053-9c13-caac0104cf2c",
  },
  {
    id: 7,
    name: "AI Begins with data",
    description: "AI Begins with data",
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: "",
    subheading: "",
    link: "",
    buttonText: "",
    isClickable: false,
    isExternal: false,
    confirmationText: "",
    popupText: "",
    screenName: "",
    weight: 2,
    files: {
      desktop: {
        filePath: "images/w-stakeholder(new).png",
        fileName: "w-stakeholder(new).png",
        fileExtension: ".png",
        fileUrl: "images/w-stakeholder(new).png",
      },
      tablet: {
        filePath: "images/t-stakeholder(new).png",
        fileName: "t-stakeholder(new).png",
        fileExtension: ".png",
        fileUrl: "images/t-stakeholder(new).png",
      },
      mobile: {
        filePath: "images/m-stakeholder(new).png",
        fileName: "m-stakeholder(new).png",
        fileExtension: ".png",
        fileUrl: "images/m-stakeholder(new).png",
      },
    },
    status: true,
    createdAt: "2025-05-05T06:44:30.587Z",
    updatedAt: "2025-05-06T07:41:50.393Z",
    createdBy: "342f5142-0955-4053-9c13-caac0104cf2c",
    updatedBy: "342f5142-0955-4053-9c13-caac0104cf2c",
  },
];

export const registrationBanners = [
  {
    id: 7,
    name: "AI Begins with data",
    description: "AI Begins with data",
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: "",
    subheading: "",
    link: "",
    buttonText: "",
    isClickable: false,
    isExternal: false,
    confirmationText: "",
    popupText: "",
    screenName: "",
    weight: 2,
    files: {
      desktop: {
        filePath: "images/w-stakeholder(new).png",
        fileName: "w-stakeholder(new).png",
        fileExtension: ".png",
        fileUrl: "images/w-stakeholder(new).png",
      },
      tablet: {
        filePath: "images/t-stakeholder(new).png",
        fileName: "t-stakeholder(new).png",
        fileExtension: ".png",
        fileUrl: "images/t-stakeholder(new).png",
      },
      mobile: {
        filePath: "images/m-stakeholder(new).png",
        fileName: "m-stakeholder(new).png",
        fileExtension: ".png",
        fileUrl: "images/m-stakeholder(new).png",
      },
    },
    status: true,
    createdAt: "2025-05-05T06:44:30.587Z",
    updatedAt: "2025-05-06T07:41:50.393Z",
    createdBy: "342f5142-0955-4053-9c13-caac0104cf2c",
    updatedBy: "342f5142-0955-4053-9c13-caac0104cf2c",
  },
  {
    id: 7,
    name: "AI Begins with data",
    description: "AI Begins with data",
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: "",
    subheading: "",
    link: "/home/pre-summit-events/apply",
    buttonText: "",
    isClickable: true,
    isExternal: false,
    confirmationText: "",
    popupText: "",
    screenName: "",
    weight: 2,
    files: {
      desktop: {
        filePath: "images/w-preSummitEvents(new)1.jpg",
        fileName: "w-preSummitEvents(new)1.jpg",
        fileExtension: ".jpg",
        fileUrl: "images/w-preSummitEvents(new)1.jpg",
      },
      tablet: {
        filePath: "images/t-preSummitEvents(new)1.jpg",
        fileName: "t-preSummitEvents(new)1.jpg",
        fileExtension: ".jpg",
        fileUrl: "images/t-preSummitEvents(new)1.jpg",
      },
      mobile: {
        filePath: "images/m-preSummitEvents(new)1.jpg",
        fileName: "m-preSummitEvents(new)1.jpg",
        fileExtension: ".jpg",
        fileUrl: "images/m-preSummitEvents(new)1.jpg",
      },
    },
    status: true,
    createdAt: "2025-05-05T06:44:30.587Z",
    updatedAt: "2025-05-06T07:41:50.393Z",
    createdBy: "342f5142-0955-4053-9c13-caac0104cf2c",
    updatedBy: "342f5142-0955-4053-9c13-caac0104cf2c",
  },
  {
    id: 7,
    name: 'AI Begins with data',
    description: 'AI Begins with data',
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: '',
    subheading: '',
    link: '/home/pre-summit-events/apply',
    buttonText: '',
    isClickable: false,
    isExternal: false,
    confirmationText: '',
    popupText: '',
    screenName: '',
    weight: 2,
    files: {
      desktop: {
        filePath: 'images/webBanner.png',
        fileName: 'webBanner.png',
        fileExtension: '.png',
        fileUrl: 'images/webBanner.png',
      },
      tablet: {
        filePath: 'images/tabletBanner.png',
        fileName: 'tabletBanner.png',
        fileExtension: '.pnSurenderg',
        fileUrl: 'images/tabletBanner.png',
      },
      mobile: {
        filePath: 'images/mobileBanner.png',
        fileName: 'tabletBanner.png',
        fileExtension: '.png',
        fileUrl: 'images/mobileBanner.png',
      },
    },
    status: true,
    createdAt: '2025-05-05T06:44:30.587Z',
    updatedAt: '2025-05-06T07:41:50.393Z',
    createdBy: '342f5142-0955-4053-9c13-caac0104cf2c',
    updatedBy: '342f5142-0955-4053-9c13-caac0104cf2c',
  },
];



export const preSummitEventsBanners = [
  {
    id: 7,
    name: "AI Begins with data",
    description: "AI Begins with data",
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: "",
    subheading: "",
    link: "/home/pre-summit-events/apply",
    buttonText: "",
    isClickable: true,
    isExternal: false,
    confirmationText: "",
    popupText: "",
    screenName: "",
    weight: 2,
    files: {
      desktop: {
        filePath: "images/w-preSummitEvents(new)1.jpg",
        fileName: "w-preSummitEvents(new)1.jpg",
        fileExtension: ".jpg",
        fileUrl: "images/w-preSummitEvents(new)1.jpg",
      },
      tablet: {
        filePath: "images/t-preSummitEvents(new)1.jpg",
        fileName: "t-preSummitEvents(new)1.jpg",
        fileExtension: ".jpg",
        fileUrl: "images/t-preSummitEvents(new)1.jpg",
      },
      mobile: {
        filePath: "images/m-preSummitEvents(new)1.jpg",
        fileName: "m-preSummitEvents(new)1.jpg",
        fileExtension: ".jpg",
        fileUrl: "images/m-preSummitEvents(new)1.jpg",
      },
    },
    status: true,
    createdAt: "2025-05-05T06:44:30.587Z",
    updatedAt: "2025-05-06T07:41:50.393Z",
    createdBy: "342f5142-0955-4053-9c13-caac0104cf2c",
    updatedBy: "342f5142-0955-4053-9c13-caac0104cf2c",
  },
];

export const aboutPreSummitEventsBanners = [
  {
    id: 7,
    name: 'AI Begins with data',
    description: 'AI Begins with data',
    forMobile: true,
    forDesktop: true,
    forTablet: true,
    active: true,
    heading: '',
    subheading: '',
    link: '/home/pre-summit-events/apply',
    buttonText: '',
    isClickable: false,
    isExternal: false,
    confirmationText: '',
    popupText: '',
    screenName: '',
    weight: 2,
    files: {
      desktop: {
        filePath: 'images/webBanner.png',
        fileName: 'webBanner.png',
        fileExtension: '.png',
        fileUrl: 'images/webBanner.png',
      },
      tablet: {
        filePath: 'images/tabletBanner.png',
        fileName: 'tabletBanner.png',
        fileExtension: '.png',
        fileUrl: 'images/tabletBanner.png',
      },
      mobile: {
        filePath: 'images/mobileBanner.png',
        fileName: 'tabletBanner.png',
        fileExtension: '.png',
        fileUrl: 'images/mobileBanner.png',
      },
    },
    status: true,
    createdAt: '2025-05-05T06:44:30.587Z',
    updatedAt: '2025-05-06T07:41:50.393Z',
    createdBy: '342f5142-0955-4053-9c13-caac0104cf2c',
    updatedBy: '342f5142-0955-4053-9c13-caac0104cf2c',
  },
];